// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"database/sql"
	"time"
)

type BankAccount struct {
	Username   string    `json:"username"`
	CardNumber string    `json:"card_number"`
	Currency   string    `json:"currency"`
	Balance    int32     `json:"balance"`
	CreatedAt  time.Time `json:"created_at"`
	UpdateAt   time.Time `json:"update_at"`
}

type Product struct {
	IDProduct     int32         `json:"id_product"`
	ProductName   string        `json:"product_name"`
	KindOfProduct string        `json:"kind_of_product"`
	Owner         string        `json:"owner"`
	Currency      string        `json:"currency"`
	Price         sql.NullInt32 `json:"price"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdateAt      time.Time     `json:"update_at"`
}

type PurchaseHistory struct {
	IDProduct  int32          `json:"id_product"`
	Buyer      string         `json:"buyer"`
	CardNumber sql.NullString `json:"card_number"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdateAt   time.Time      `json:"update_at"`
}

type User struct {
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
