// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"
)

type BankAccount struct {
	Username   string    `json:"username"`
	CardNumber string    `json:"card_number"`
	Balance    int32     `json:"balance"`
	Currency   string    `json:"currency"`
	CreatedAt  time.Time `json:"created_at"`
	UpdateAt   time.Time `json:"update_at"`
}

type Product struct {
	IDProduct     int32     `json:"id_product"`
	ProductName   string    `json:"product_name"`
	KindOfProduct string    `json:"kind_of_product"`
	Owner         string    `json:"owner"`
	Currency      string    `json:"currency"`
	Price         int32     `json:"price"`
	Quantity      int32     `json:"quantity"`
	CreatedAt     time.Time `json:"created_at"`
	UpdateAt      time.Time `json:"update_at"`
}

type PurchaseHistory struct {
	IDPurchaseHistory int32     `json:"id_purchase_history"`
	IDProduct         int32     `json:"id_product"`
	Buyer             string    `json:"buyer"`
	CardNumberOfBuyer string    `json:"card_number_of_buyer"`
	CreatedAt         time.Time `json:"created_at"`
	UpdateAt          time.Time `json:"update_at"`
}

type User struct {
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	Level             bool      `json:"level"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
